//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Star_Catalog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locales() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Star_Catalog.Resources.Locales", typeof(Locales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created with Xamarin.Forms.
        /// </summary>
        internal static string About_XamarinText {
            get {
                return ResourceManager.GetString("About_XamarinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is created as a project for a course at the Belorussian State University of Informatics and Radioelectronics..
        /// </summary>
        internal static string AboutApp_Text {
            get {
                return ResourceManager.GetString("AboutApp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayer:.
        /// </summary>
        internal static string Bayer {
            get {
                return ResourceManager.GetString("Bayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayer/Flamsteed designation:.
        /// </summary>
        internal static string BF {
            get {
                return ResourceManager.GetString("BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gliese Catalog:.
        /// </summary>
        internal static string Gliese {
            get {
                return ResourceManager.GetString("Gliese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henry Draper catalog:.
        /// </summary>
        internal static string HD {
            get {
                return ResourceManager.GetString("HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hipparcos catalog:.
        /// </summary>
        internal static string HIP {
            get {
                return ResourceManager.GetString("HIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvard Revised catalog:.
        /// </summary>
        internal static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aphelion:.
        /// </summary>
        internal static string Info_Aphelion {
            get {
                return ResourceManager.GetString("Info_Aphelion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AU.
        /// </summary>
        internal static string Info_AU {
            get {
                return ResourceManager.GetString("Info_AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristics.
        /// </summary>
        internal static string Info_Characteristics {
            get {
                return ResourceManager.GetString("Info_Characteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color index (B-V):.
        /// </summary>
        internal static string Info_CI {
            get {
                return ResourceManager.GetString("Info_CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constellation:.
        /// </summary>
        internal static string Info_Constellation {
            get {
                return ResourceManager.GetString("Info_Constellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string Info_Days {
            get {
                return ResourceManager.GetString("Info_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density:.
        /// </summary>
        internal static string Info_Density {
            get {
                return ResourceManager.GetString("Info_Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Info_Description {
            get {
                return ResourceManager.GetString("Info_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designations:.
        /// </summary>
        internal static string Info_Designations {
            get {
                return ResourceManager.GetString("Info_Designations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter:.
        /// </summary>
        internal static string Info_Diameter {
            get {
                return ResourceManager.GetString("Info_Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        internal static string Info_Distance {
            get {
                return ResourceManager.GetString("Info_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eccentricity:.
        /// </summary>
        internal static string Info_Eccentricity {
            get {
                return ResourceManager.GetString("Info_Eccentricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity:.
        /// </summary>
        internal static string Info_Gravity {
            get {
                return ResourceManager.GetString("Info_Gravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminocity:.
        /// </summary>
        internal static string Info_Luminocity {
            get {
                return ResourceManager.GetString("Info_Luminocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ly.
        /// </summary>
        internal static string Info_LY {
            get {
                return ResourceManager.GetString("Info_LY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnitude:.
        /// </summary>
        internal static string Info_Magnitude {
            get {
                return ResourceManager.GetString("Info_Magnitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass:.
        /// </summary>
        internal static string Info_Mass {
            get {
                return ResourceManager.GetString("Info_Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Info_Meters {
            get {
                return ResourceManager.GetString("Info_Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Info_Name {
            get {
                return ResourceManager.GetString("Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbital period:.
        /// </summary>
        internal static string Info_OrbitalP {
            get {
                return ResourceManager.GetString("Info_OrbitalP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbital speed:.
        /// </summary>
        internal static string Info_OrbitalS {
            get {
                return ResourceManager.GetString("Info_OrbitalS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pc.
        /// </summary>
        internal static string Info_Parsec {
            get {
                return ResourceManager.GetString("Info_Parsec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perihelion:.
        /// </summary>
        internal static string Info_Perihelion {
            get {
                return ResourceManager.GetString("Info_Perihelion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius:.
        /// </summary>
        internal static string Info_Radius {
            get {
                return ResourceManager.GetString("Info_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R🜨.
        /// </summary>
        internal static string Info_RadiusEarth {
            get {
                return ResourceManager.GetString("Info_RadiusEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellites:.
        /// </summary>
        internal static string Info_Satellites {
            get {
                return ResourceManager.GetString("Info_Satellites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-major axis:.
        /// </summary>
        internal static string Info_SemiMajor {
            get {
                return ResourceManager.GetString("Info_SemiMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectral type:.
        /// </summary>
        internal static string Info_Spectral {
            get {
                return ResourceManager.GetString("Info_Spectral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightest stars:.
        /// </summary>
        internal static string Info_Stars {
            get {
                return ResourceManager.GetString("Info_Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synodical period:.
        /// </summary>
        internal static string Info_Synodic {
            get {
                return ResourceManager.GetString("Info_Synodic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature:.
        /// </summary>
        internal static string Info_Temperature {
            get {
                return ResourceManager.GetString("Info_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string Info_Type {
            get {
                return ResourceManager.GetString("Info_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial velocity:.
        /// </summary>
        internal static string Info_Velocity {
            get {
                return ResourceManager.GetString("Info_Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/sec.
        /// </summary>
        internal static string Info_VelocityDim {
            get {
                return ResourceManager.GetString("Info_VelocityDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string Info_Weight {
            get {
                return ResourceManager.GetString("Info_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M🜨.
        /// </summary>
        internal static string Info_WeightEarth {
            get {
                return ResourceManager.GetString("Info_WeightEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Settings_Apply {
            get {
                return ResourceManager.GetString("Settings_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Settings_Lang {
            get {
                return ResourceManager.GetString("Settings_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Беларуская.
        /// </summary>
        internal static string Settings_LangBY {
            get {
                return ResourceManager.GetString("Settings_LangBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Settings_LangEN {
            get {
                return ResourceManager.GetString("Settings_LangEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Settings_LangRU {
            get {
                return ResourceManager.GetString("Settings_LangRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, restart the application.
        /// </summary>
        internal static string Settings_Restart {
            get {
                return ResourceManager.GetString("Settings_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constellations.
        /// </summary>
        internal static string Title_Constellations {
            get {
                return ResourceManager.GetString("Title_Constellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep-sky objects.
        /// </summary>
        internal static string Title_DSO {
            get {
                return ResourceManager.GetString("Title_DSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Title_Info {
            get {
                return ResourceManager.GetString("Title_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planets.
        /// </summary>
        internal static string Title_Planets {
            get {
                return ResourceManager.GetString("Title_Planets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Options.
        /// </summary>
        internal static string Title_Sort {
            get {
                return ResourceManager.GetString("Title_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        internal static string Title_Stars {
            get {
                return ResourceManager.GetString("Title_Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Starrs! - astronomical catalog..
        /// </summary>
        internal static string Welcome_Text {
            get {
                return ResourceManager.GetString("Welcome_Text", resourceCulture);
            }
        }
    }
}
